---
- name: Pull Docker image of Frontend
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      shell: docker pull vamshi07/frontend:latest
    - name: Running container
      shell: docker create -it  --name frontend vamshi07/frontend